# 4 Numpy基础：数组和矢量计算

In [2]:
import numpy as  np
my_arr = np.arange(10000000)
my_list = list(range(1000000))

In [27]:
% time for _ in range(1000):my_arr2 = my_arr * 2

Wall time: 17.6 ms


In [29]:
% time for _ in range(1000): my_list2 = [x*2 for x in my_list]

Wall time: 631 ms


In [30]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.78534246, -1.01819696,  0.40053866],
       [-0.57564644,  0.25712332, -0.58085042]])

In [31]:
data *10

array([[  7.85342463, -10.18196962,   4.00538664],
       [ -5.7564644 ,   2.57123322,  -5.80850422]])

In [32]:
data + data

array([[ 1.57068493, -2.03639392,  0.80107733],
       [-1.15129288,  0.51424664, -1.16170084]])

In [33]:
data.shape

(2, 3)

In [34]:
data.dtype

dtype('float64')

In [35]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [37]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr2.ndim


2

In [39]:
arr2.shape

(2, 4)

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr1.dtype

dtype('float64')

In [42]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [43]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [44]:
np.empty((2,3,2))

array([[[  1.15117295e-321,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [45]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [47]:
arr1.dtype

dtype('float64')

In [48]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [50]:
float_arr = arr.astype(np.float64)

In [51]:
float_arr.dtype

dtype('float64')

In [52]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [53]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [56]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [59]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380],dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [60]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [61]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [62]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [63]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [64]:
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [65]:
arr2 = np.array([[0.,4.,1.,],[7.,2.,12.]])
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [66]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [67]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]

5

In [69]:
arr[5:8]

array([5, 6, 7])

In [70]:
arr[5:8] = 12

In [71]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [72]:
arr_slice = arr[5:8]

In [73]:
arr_slice

array([12, 12, 12])

In [74]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [75]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [80]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [81]:
arr2d[2]

array([7, 8, 9])

In [82]:
arr2d[0][2]

3

In [83]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [87]:
arr = np.empty((8,4))
arr[1]

array([  2.16565217e-316,   8.62526556e-315,   8.62526303e-315,
         2.16496799e-316])

In [89]:
for i in range(8):
    arr[i]=i

In [90]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [91]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [92]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [93]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [94]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [95]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [97]:
arr = np.random.randn(6,3)
arr

array([[-0.57098771, -0.07069365,  0.91390859],
       [ 1.27713878,  1.60860937,  0.88657072],
       [ 0.68314426,  0.28827323, -0.99302662],
       [-0.41301124, -2.05622564, -0.6861222 ],
       [ 0.93807492,  1.1650559 , -1.00106928],
       [ 0.63987494,  1.03004018,  1.07452119]])

In [98]:
np.dot(arr.T, arr)

array([[ 3.88379927,  4.89296573, -0.03607978],
       [ 4.89296573,  9.32212508,  2.42659584],
       [-0.03607978,  2.42659584,  5.23483759]])

In [101]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [103]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [104]:
x = np.random.randn(8)
y = np.random.randn(8)

In [105]:
np.maximum(x,y)

array([ 1.2040052 ,  0.41506137,  0.74003769,  0.90129755,  1.70522966,
        0.60196075,  0.05237292,  0.17489736])

In [106]:
arr = np.random.randn(7)*5

In [107]:
arr

array([ 1.96033195, -1.39894951,  1.85959676, -5.97085989, -6.70161772,
        6.02632249, -4.50919903])

In [108]:
remainder, whole_part = np.modf(arr)

In [109]:
remainder

array([ 0.96033195, -0.39894951,  0.85959676, -0.97085989, -0.70161772,
        0.02632249, -0.50919903])

In [110]:
whole_part

array([ 1., -1.,  1., -5., -6.,  6., -4.])

In [111]:
points = np.arange(-5,5,0.01)
xs , ys = np.meshgrid(points, points)

In [112]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [113]:
z = np.sqrt(xs**2 + ys**2)

In [114]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [118]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()

In [117]:
plt.title('---')

Text(0.5,1,'---')