# 5 pandas入门

Series

In [18]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [15]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
'b' in obj2

True

In [24]:
sdata = {'ohio':35000,'texas':71000,'oregon':16000,'utah':5000}

In [25]:
obj3 = pd.Series(sdata)

In [26]:
obj3

ohio      35000
oregon    16000
texas     71000
utah       5000
dtype: int64

In [30]:
states = ['california', 'ohio','oregon','texas']
obj4 = pd.Series(sdata, index=states) 

In [31]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [32]:
pd.isnull(obj4)

california     True
ohio          False
oregon        False
texas         False
dtype: bool

In [33]:
pd.notnull(obj4)

california    False
ohio           True
oregon         True
texas          True
dtype: bool

In [34]:
obj4.isnull()

california     True
ohio          False
oregon        False
texas         False
dtype: bool

In [35]:
obj3

ohio      35000
oregon    16000
texas     71000
utah       5000
dtype: int64

In [36]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [37]:
obj3+obj4

california         NaN
ohio           70000.0
oregon         32000.0
texas         142000.0
utah               NaN
dtype: float64

In [38]:
obj4.name = 'population'
obj4.index.name = 'state'

In [39]:
obj4

state
california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
Name: population, dtype: float64

In [45]:
obj

0    4
1    7
2   -5
3    3
d    6
dtype: int64

In [46]:
obj.index=['Bod','Steve','Jeff','Ryan','wo']

In [47]:
obj

Bod      4
Steve    7
Jeff    -5
Ryan     3
wo       6
dtype: int64

DaraFrame

In [49]:
data = {'state':['ohio','ohio','ohio','nevada','nevada','nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]
       }
frame = pd.DataFrame(data)

In [50]:
frame

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002
5  3.2  nevada  2003

In [51]:
frame.head()

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002

In [52]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])

In [53]:
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  nevada  2.4  NaN
five   2002  nevada  2.9  NaN
six    2003  nevada  3.2  NaN

In [54]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [55]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     nevada
five     nevada
six      nevada
Name: state, dtype: object

In [56]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [57]:
frame2.loc['three']

year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [58]:
frame2['debt'] = 16.5

In [59]:
frame2

year   state  pop  debt
one    2000    ohio  1.5  16.5
two    2001    ohio  1.7  16.5
three  2002    ohio  3.6  16.5
four   2001  nevada  2.4  16.5
five   2002  nevada  2.9  16.5
six    2003  nevada  3.2  16.5

In [62]:
frame2['debt']=np.arange(6.0)

In [63]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   0.0
two    2001    ohio  1.7   1.0
three  2002    ohio  3.6   2.0
four   2001  nevada  2.4   3.0
five   2002  nevada  2.9   4.0
six    2003  nevada  3.2   5.0

In [64]:
val = pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])

In [65]:
frame2['debt'] = val

In [67]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [68]:
frame2['eastern'] = frame2.state == 'ohio'

In [70]:
frame2

year   state  pop  debt  eastern
one    2000    ohio  1.5   NaN     True
two    2001    ohio  1.7  -1.2     True
three  2002    ohio  3.6   NaN     True
four   2001  nevada  2.4  -1.5    False
five   2002  nevada  2.9  -1.7    False
six    2003  nevada  3.2   NaN    False

In [71]:
del frame2['eastern']

In [72]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [73]:
pop = {'nevada':{2001:2.4,2002:2.9},'ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [74]:
frame3 = pd.DataFrame(pop)

In [76]:
frame3

nevada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
frame3.T

2000  2001  2002
nevada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

In [78]:
pd.DataFrame(pop,index=[2001,2002,2003])

nevada  ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [79]:
frame3.index.name = 'year';frame3.columns.name = 'state'


In [80]:
frame3

state  nevada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [81]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [82]:
frame2.values


array([[2000, 'ohio', 1.5, nan],
       [2001, 'ohio', 1.7, -1.2],
       [2002, 'ohio', 3.6, nan],
       [2001, 'nevada', 2.4, -1.5],
       [2002, 'nevada', 2.9, -1.7],
       [2003, 'nevada', 3.2, nan]], dtype=object)

In [83]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int32

In [84]:
index = obj.index

In [85]:
index

Index(['a', 'b', 'c'], dtype='object')

In [87]:
index[1:,]

Index(['b', 'c'], dtype='object')

In [88]:
frame3

state  nevada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [89]:
frame3.columns

Index(['nevada', 'ohio'], dtype='object', name='state')

In [90]:
'ohio' in frame3.columns


True

In [91]:
2003 in frame3.columns

False

In [92]:
dup_lables = pd.Index(['foo','foo','bar','bar'])

In [94]:
dup_lables

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

5.2基本功能

In [95]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index = ['d','b','a','c'])

In [96]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [97]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [98]:
obj2


a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [99]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [101]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [103]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'],columns=['ohio','texas','california'])

In [104]:
frame

ohio  texas  california
a     0      1           2
c     3      4           5
d     6      7           8

In [105]:
frame2 = frame.reindex(['a','b','c','d'])

In [106]:
frame2

ohio  texas  california
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [109]:
states = ['texas','Utah','california']
frame.reindex(columns=states)

texas  Utah  california
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [110]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [111]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [112]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [113]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [114]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','new york'],columns=['one','two','three','four'])

In [115]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [116]:
data.drop(['colorado','ohio'])

one  two  three  four
utah        8    9     10    11
new york   12   13     14    15

In [117]:
data.drop('two',axis=1)

one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
new york   12     14    15

In [118]:
data.drop(['two','four'], axis = 'columns')

one  three
ohio        0      2
colorado    4      6
utah        8     10
new york   12     14

In [119]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [120]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])

In [121]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [122]:
obj['b']

1.0

In [123]:
obj[1]

1.0

In [124]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [125]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [126]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [127]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [128]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [129]:
obj['b':'c'] = 5

In [130]:
obj


a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [131]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['ohio','colorado','utah','new york'],columns=['one','two','three','four'])

In [132]:
data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [133]:
data['two']

ohio         1
colorado     5
utah         9
new york    13
Name: two, dtype: int32

In [134]:
data[['three','one']]

three  one
ohio          2    0
colorado      6    4
utah         10    8
new york     14   12

In [135]:
data[:2]

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7

In [137]:
data[data['three']>5]

one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [138]:
data < 5

one    two  three   four
ohio       True   True   True   True
colorado   True  False  False  False
utah      False  False  False  False
new york  False  False  False  False

In [139]:
data[data<5]=0

In [140]:
data

one  two  three  four
ohio        0    0      0     0
colorado    0    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [141]:
data

one  two  three  four
ohio        0    0      0     0
colorado    0    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [142]:
data.loc['colorado',['two','three']]

two      5
three    6
Name: colorado, dtype: int32

In [143]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: utah, dtype: int32

In [144]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: utah, dtype: int32

In [145]:
data.iloc[[1,2],[3,0,1]]

four  one  two
colorado     7    0    5
utah        11    8    9

In [146]:
data.loc[:'utah','two']

ohio        0
colorado    5
utah        9
Name: two, dtype: int32

In [147]:
data


one  two  three  four
ohio        0    0      0     0
colorado    0    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [148]:
data.iloc[:,:3][data.three>5]

one  two  three
colorado    0    5      6
utah        8    9     10
new york   12   13     14

In [150]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [151]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [152]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [153]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [154]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [157]:
df1 =  pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['ohio','texas','colorado'])

In [160]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['utah','ohio','texas','oregon'])

In [161]:
df1

b    c    d
ohio      0.0  1.0  2.0
texas     3.0  4.0  5.0
colorado  6.0  7.0  8.0

In [162]:
df2

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [163]:
df1+df2

b   c     d   e
colorado  NaN NaN   NaN NaN
ohio      3.0 NaN   6.0 NaN
oregon    NaN NaN   NaN NaN
texas     9.0 NaN  12.0 NaN
utah      NaN NaN   NaN NaN

In [164]:
df1 = pd.DataFrame({'a':[1,2]})

In [166]:
df2 = pd.DataFrame({'b':[3,4]})

In [167]:
df1

a
0  1
1  2

In [168]:
df2

b
0  3
1  4

In [169]:
df1 - df2

a   b
0 NaN NaN
1 NaN NaN

In [170]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [171]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [172]:
df2.loc[1,'b'] = np.nan

In [173]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [174]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [175]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [176]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [177]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [178]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [179]:
1/ df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [180]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [181]:
arr = np.arange(12.).reshape((3,4))

In [182]:
arr


array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [183]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [184]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [186]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['utah','ohio','texas','oregon'])

In [187]:
series = frame.iloc[0]

In [188]:
frame

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [189]:
series

b    0.0
d    1.0
e    2.0
Name: utah, dtype: float64

In [190]:
frame - series

b    d    e
utah    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
oregon  9.0  9.0  9.0

In [191]:
series2 = pd.Series(range(3), index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int32

In [192]:
frame

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [193]:
frame + series2

b   d     e   f
utah    0.0 NaN   3.0 NaN
ohio    3.0 NaN   6.0 NaN
texas   6.0 NaN   9.0 NaN
oregon  9.0 NaN  12.0 NaN

In [195]:
series3 = frame['d']

In [196]:
frame

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [197]:
series3

utah       1.0
ohio       4.0
texas      7.0
oregon    10.0
Name: d, dtype: float64

In [198]:
frame.sub(series3,axis = 'index')

b    d    e
utah   -1.0  0.0  1.0
ohio   -1.0  0.0  1.0
texas  -1.0  0.0  1.0
oregon -1.0  0.0  1.0

In [199]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['utah','ohio','texas','oregon'])

In [200]:
frame

b         d         e
utah   -0.251189 -0.561296 -0.551372
ohio    1.401951 -0.272004 -0.230629
texas  -0.141839  0.467953  0.540881
oregon -0.515580 -0.119927  0.928043

In [201]:
np.abs(frame)

b         d         e
utah    0.251189  0.561296  0.551372
ohio    1.401951  0.272004  0.230629
texas   0.141839  0.467953  0.540881
oregon  0.515580  0.119927  0.928043

In [202]:
f = lambda x: x.max()-x.min()

In [203]:
frame.apply(f)

b    1.917531
d    1.029249
e    1.479415
dtype: float64

In [204]:
frame.apply(f, axis='columns')

utah      0.310107
ohio      1.673955
texas     0.682720
oregon    1.443623
dtype: float64

In [205]:
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])

In [206]:
frame.apply(f)

b         d         e
min -0.515580 -0.561296 -0.551372
max  1.401951  0.467953  0.928043

In [207]:
obj = pd.Series(range(4), index=['d','a','b','c'])

In [208]:
obj.sort_index()


a    1
b    2
c    3
d    0
dtype: int32

In [209]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [210]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [211]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [212]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [213]:
obj = pd.Series([4,7,-3,2])

In [214]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [215]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [216]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [217]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [218]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [219]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [220]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [222]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [223]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [224]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [226]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

In [227]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [228]:
obj.index.is_unique

False

In [230]:
obj['a']

a    0
a    1
dtype: int32

In [231]:
obj['c']

4